#ifndef ETCDATA_H_
#define ETCDATA_H_

#include "image.h"

#define ARRAYSTOPPER 255

/*
  enum{
  BODY_SAMPLE,BODY_NORMAL0,BODY_NORMAL1,BODY_WOW,
  BODY_HEY,BODY_THAT,BODY_BACK,BODY_SIT,BODY_LIE,BODY_SLEEP0,BODY_SLEEP1,
  BODY_DIE,BODY_WHAT,BODY_TYOKON,BODY_MOJI0,BODY_MOJI1,BODY_IMAGENUM,
  };
  enum{
  EYE_NORMAL,EYE_SLEEPY0,EYE_SLEEPY1,EYE_CLOSE,EYE_HAPPY,EYE_SURPRISE,
  EYE_ZITO,EYE_HOW,EYE_WINK,EYE_HIDE
  };
*/

const uint8_t anime_normal[17][2] PROGMEM = {
  {BODY_NORMAL0,EYE_NORMAL},
  {BODY_NORMAL0,EYE_NORMAL},
  {BODY_NORMAL0,EYE_NORMAL},
  {BODY_NORMAL1,EYE_NORMAL},
  {BODY_NORMAL1,EYE_NORMAL},
  
  {BODY_NORMAL1,EYE_NORMAL},
  {BODY_NORMAL1,EYE_NORMAL},
  {BODY_NORMAL0,EYE_NORMAL},
  {BODY_NORMAL0,EYE_NORMAL},
  {BODY_NORMAL0,EYE_NORMAL},
  
  {BODY_NORMAL0,EYE_NORMAL},
  {BODY_NORMAL0,EYE_NORMAL},
  {BODY_NORMAL1,EYE_NORMAL},
  {BODY_NORMAL1,EYE_NORMAL},
  {BODY_NORMAL1,EYE_NORMAL},
  
  {BODY_NORMAL0,EYE_NORMAL},
  {ARRAYSTOPPER, ARRAYSTOPPER},
};


const uint8_t anime_happy[2][2] PROGMEM = {
  {BODY_NORMAL0,EYE_HAPPY},
  {ARRAYSTOPPER,ARRAYSTOPPER},
};

const uint8_t anime_zito[2][2] PROGMEM = {
  {BODY_NORMAL0,EYE_ZITO},
  {ARRAYSTOPPER,ARRAYSTOPPER},
};

const uint8_t anime_die[2][2] PROGMEM = {
  {BODY_DIE,EYE_HIDE},
  {ARRAYSTOPPER,ARRAYSTOPPER},
};

const uint8_t anime_sleeping[19][2] PROGMEM = {
  {BODY_SLEEP0,EYE_CLOSE},
  {BODY_SLEEP0,EYE_CLOSE},
  {BODY_SLEEP0,EYE_CLOSE},
  {BODY_SLEEP0,EYE_CLOSE},
  {BODY_SLEEP0,EYE_CLOSE},
  
  {BODY_SLEEP0,EYE_CLOSE},
  {BODY_SLEEP0,EYE_CLOSE},
  {BODY_SLEEP0,EYE_CLOSE},
  {BODY_SLEEP0,EYE_CLOSE},
  {BODY_SLEEP1,EYE_CLOSE},
  
  {BODY_SLEEP1,EYE_CLOSE},
  {BODY_SLEEP1,EYE_CLOSE},
  {BODY_SLEEP1,EYE_CLOSE},
  {BODY_SLEEP1,EYE_CLOSE},
  {BODY_SLEEP1,EYE_CLOSE},
  
  {BODY_SLEEP1,EYE_CLOSE},
  {BODY_SLEEP1,EYE_CLOSE},
  {BODY_SLEEP1,EYE_CLOSE},
  {ARRAYSTOPPER, ARRAYSTOPPER},
};

const uint8_t anime_sleepy[31][2] PROGMEM = {
  {BODY_SIT,EYE_SLEEPY0},
  {BODY_SIT,EYE_SLEEPY0},
  {BODY_SIT,EYE_SLEEPY0},
  {BODY_SIT,EYE_SLEEPY0},
  {BODY_SIT,EYE_SLEEPY0},
  
  {BODY_SIT,EYE_SLEEPY0},
  {BODY_SIT,EYE_SLEEPY0},
  {BODY_SIT,EYE_SLEEPY0},
  {BODY_SIT,EYE_SLEEPY0},
  {BODY_SIT,EYE_SLEEPY0},
  
  {BODY_SIT,EYE_SLEEPY1},
  {BODY_SIT,EYE_SLEEPY1},  
  {BODY_SIT,EYE_SLEEPY1},
  {BODY_SIT,EYE_SLEEPY1},
  {BODY_SIT,EYE_SLEEPY1},
  
  {BODY_SIT,EYE_SLEEPY1},
  {BODY_SIT,EYE_SLEEPY1},  
  {BODY_SIT,EYE_SLEEPY1},
  {BODY_SIT,EYE_SLEEPY1},
  {BODY_SIT,EYE_SLEEPY1},
  
  {BODY_SIT,EYE_CLOSE},
  {BODY_SIT,EYE_CLOSE},  
  {BODY_SIT,EYE_CLOSE},
  {BODY_SIT,EYE_CLOSE},
  {BODY_SIT,EYE_CLOSE},
  
  {BODY_SIT,EYE_CLOSE},
  {BODY_SIT,EYE_CLOSE},
  {BODY_SIT,EYE_CLOSE},
  {BODY_SIT,EYE_CLOSE},
  {BODY_SIT,EYE_CLOSE},
  
  {ARRAYSTOPPER, ARRAYSTOPPER},
};

const uint8_t anime_stroke[9][2] PROGMEM = {
  {BODY_NORMAL0,EYE_CLOSE},
  {BODY_NORMAL0,EYE_CLOSE},
  {BODY_STROKE,EYE_CLOSE},
  {BODY_STROKE,EYE_CLOSE},
  {BODY_NORMAL0,EYE_CLOSE},
  
  {BODY_NORMAL0,EYE_CLOSE},
  {BODY_STROKE,EYE_CLOSE},
  {BODY_STROKE,EYE_CLOSE},
  {ARRAYSTOPPER, ARRAYSTOPPER},
};

const uint8_t anime_stroke_happy[9][2] PROGMEM = {
  {BODY_NORMAL0,EYE_SAD},
  {BODY_NORMAL0,EYE_SAD},
  {BODY_STROKE,EYE_SAD},
  {BODY_STROKE,EYE_SAD},
  {BODY_NORMAL0,EYE_SAD},
  
  {BODY_NORMAL0,EYE_SAD},
  {BODY_STROKE,EYE_SAD},
  {BODY_STROKE,EYE_SAD}, 
  {ARRAYSTOPPER, ARRAYSTOPPER},
};

const uint8_t anime_stroke_angry[9][2] PROGMEM = {
  {BODY_NORMAL0,EYE_ANGRY},
  {BODY_NORMAL0,EYE_ANGRY},
  {BODY_STROKE,EYE_ANGRY},
  {BODY_STROKE,EYE_ANGRY},
  {BODY_NORMAL0,EYE_ANGRY},
  
  {BODY_NORMAL0,EYE_ANGRY},
  {BODY_STROKE,EYE_ANGRY},
  {BODY_STROKE,EYE_ANGRY},   
  {ARRAYSTOPPER, ARRAYSTOPPER},
};

const uint8_t anime_call[5][2] PROGMEM = {
  {BODY_WOW,EYE_HAU},
  {BODY_WOW,EYE_HAU},  
  {BODY_WOW,EYE_HAU},
  {BODY_WOW,EYE_HAU},
  {FLIPBODY,ARRAYSTOPPER},
};

const uint8_t anime_dance[3][2] PROGMEM = {
  {BODY_WOW,EYE_HAPPY},
  {BODY_WOW,EYE_HAPPY},   
  {FLIPBODY,ARRAYSTOPPER},
};

const uint8_t anime_eat[13][2] PROGMEM = {
  {BODY_NORMAL1,EYE_NORMAL},
  {BODY_NORMAL1,EYE_NORMAL},
  {BODY_STROKE,EYE_CLOSE},
  {BODY_STROKE,EYE_CLOSE},
  {BODY_NORMAL0,EYE_NORMAL},
  
  {BODY_NORMAL0,EYE_NORMAL},  
  {BODY_STROKE,EYE_CLOSE},  
  {BODY_STROKE,EYE_CLOSE},
  {BODY_NORMAL1,EYE_NORMAL},  
  {BODY_NORMAL1,EYE_NORMAL}, 
   
  {BODY_STROKE,EYE_CLOSE},  
  {BODY_STROKE,EYE_CLOSE},
  {ARRAYSTOPPER,ARRAYSTOPPER},
};

const uint8_t anime_eat_storage[13][2] PROGMEM = {
  {BODY_NORMAL1,EYE_NORMAL},
  {BODY_NORMAL1,EYE_NORMAL},
  {BODY_STROKE,EYE_CLOSE},
  {BODY_STROKE,EYE_CLOSE},
  {BODY_NORMAL0,EYE_NORMAL},
  
  {BODY_NORMAL0,EYE_NORMAL},  
  {BODY_STROKE,EYE_CLOSE},  
  {BODY_STROKE,EYE_CLOSE},
  {BODY_NORMAL1,EYE_NORMAL},  
  {BODY_NORMAL1,EYE_NORMAL}, 
   
  {BODY_STROKE,EYE_CLOSE},  
  {BODY_STROKE,EYE_CLOSE},
  {ARRAYSTOPPER,ARRAYSTOPPER},
};



enum{
  ANIME_NORMAL,ANIME_HAPPY,ANIME_ZITO,
  ANIME_DIE,ANIME_SLEEPING,ANIME_SLEEPY,
  ANIME_STROKE,ANIME_STROKE_HAPPY,ANIME_STROKE_ANGRY,
  ANIME_DANCE,ANIME_CALL,ANIME_EAT,
  ANIME_STORAGE_EAT,
  ANIME_NUM
};

const uint8_t* animations[ANIME_NUM] PROGMEM = {
  &anime_normal[0][0],
  &anime_happy[0][0],
  &anime_zito[0][0],
  &anime_die[0][0],
  &anime_sleeping[0][0],
  &anime_sleepy[0][0],
  &anime_stroke[0][0],
  &anime_stroke_happy[0][0],
  &anime_stroke_angry[0][0],  
  &anime_dance[0][0],
  &anime_call[0][0],
  &anime_eat[0][0],
  &anime_eat_storage[0][0],
};


const uint8_t foodLevel[11] PROGMEM = {
  2, 3, 4, 
  3, 2, 4, 
  4, 4, 1,
  3, 3,
};

#endif
